# -*- coding: utf-8 -*-
"""cnn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TJ9UwvFWEpQ_JJKFXi9yZNRbf5-h6JkZ
"""

from google.colab import drive
drive.mount('/content/drive')

data_path = "/content/drive/MyDrive/MY_data"

# ===== IMPORTS =====
import os
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F

from torchvision import datasets, transforms, models
from torch.utils.data import DataLoader

from PIL import Image

device=torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(device)

# ===== PATHS =====
train_path = r"/content/drive/MyDrive/MY_data/train"
test_path  = r"/content/drive/MyDrive/MY_data/test"
pred_path  = r"/content/drive/MyDrive/MY_data/predict"

# ===== DATA INFO =====
classes = sorted(os.listdir(train_path))
print("Classes:", classes)
print("Number of classes:", len(classes))

def count_images(path):
    total = 0
    for c in os.listdir(path):
        total += len(os.listdir(os.path.join(path, c)))
    return total

print("Train images:", count_images(train_path))
print("Test images:", count_images(test_path))

# ===== TRANSFORMS =====
train_transform = transforms.Compose([
    transforms.Resize((224,224)),
    transforms.RandomHorizontalFlip(),
    transforms.RandomRotation(15),
    transforms.ColorJitter(),
    transforms.ToTensor(),
    transforms.Normalize([0.485,0.456,0.406],
                         [0.229,0.224,0.225])
])

test_transform = transforms.Compose([
    transforms.Resize((224,224)),
    transforms.ToTensor(),
    transforms.Normalize([0.485,0.456,0.406],
                         [0.229,0.224,0.225])
])

# ===== DATASETS =====
train_data = datasets.ImageFolder(train_path, transform=train_transform)
test_data  = datasets.ImageFolder(test_path, transform=test_transform)

# ===== DATALOADERS =====
train_loader = DataLoader(train_data, batch_size=32, shuffle=True)
test_loader  = DataLoader(test_data, batch_size=32, shuffle=False)

# ===== MODEL =====

model = models.resnet18(pretrained=True)

model.fc = nn.Linear(model.fc.in_features, len(classes))

model = model.to(device)

criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.0001)

# ===== TRAINING =====
for epoch in range(50):
    model.train()
    total_loss = 0

    for images, labels in train_loader:
        images, labels = images.to(device), labels.to(device)

        outputs = model(images)
        loss = criterion(outputs, labels)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        total_loss += loss.item()

    print(f"Epoch {epoch+1}, Loss: {total_loss:.4f}")

# ===== TESTING =====
correct = 0
total = 0

model.eval()
with torch.no_grad():
    for images, labels in test_loader:
        images, labels = images.to(device), labels.to(device)

        outputs = model(images)
        _, preds = torch.max(outputs, 1)

        total += labels.size(0)
        correct += (preds == labels).sum().item()

print("Accuracy:", 100*correct/total, "%")

# ===== SAMPLE PREDICTIONS =====
images, labels = next(iter(test_loader))

images = images.to(device)
outputs = model(images)
_, preds = torch.max(outputs,1)

for i in range(10):
    print("Pred:", classes[preds[i].item()],
          "| Actual:", classes[labels[i].item()])

import matplotlib.pyplot as plt

model.eval()

for img_name in os.listdir(pred_path):
    img_path = os.path.join(pred_path, img_name)

    img = Image.open(img_path).convert("RGB")

    img_tensor = test_transform(img).unsqueeze(0).to(device)

    with torch.no_grad():
        output = model(img_tensor)
        _, pred = torch.max(output, 1)

    label = classes[pred.item()]

    plt.imshow(img)
    plt.title(f"Prediction: {label}")
    plt.axis("off")
    plt.show()

    print(img_name, "→", label)